# Generated by Django 5.2 on 2025-09-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_model',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AddField(
            model_name='site_model',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سایت'),
        ),
    ]
