# Generated by Django 5.2 on 2025-09-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_site_model_options_site_model_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_model',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
