# Generated by Django 5.2 on 2025-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_site_model_copyright_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_model',
            name='copyright_text',
            field=models.CharField(default='default-copyright_text', max_length=50, verbose_name='متن کپی رایت'),
        ),
        migrations.AlterField(
            model_name='site_model',
            name='site_name',
            field=models.CharField(default='default-name', max_length=200, verbose_name='نام سایت'),
        ),
    ]
