# Generated by Django 5.2 on 2025-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_read_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/خوانده نشده'),
        ),
    ]
