# Generated by Django 5.2 on 2025-10-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_is_read_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(max_length=300, verbose_name='پیام مشتری'),
        ),
    ]
