# Generated by Django 5.2 on 2025-09-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='خدمات که ارائه میدی')),
                ('projects', models.CharField(max_length=50, verbose_name='تعداد پروژه که انجام دادی')),
                ('descreption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
        ),
    ]
