# Generated by Django 5.2 on 2025-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم به اینگلیسی برای ایکون'),
        ),
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک برای بیشتر بخوانید'),
        ),
    ]
