# Generated by Django 5.2 on 2025-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_icon_services_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=50, verbose_name='تایپ پلن مثال  :استاندارد , پریمیرم')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت پلن ها')),
                ('ops1', models.CharField(blank=True, max_length=50, null=True, verbose_name='قابلیت های پلن')),
                ('ops2', models.CharField(blank=True, max_length=50, null=True, verbose_name='قابلیت های پلن')),
                ('ops3', models.CharField(blank=True, max_length=50, null=True, verbose_name='قابلیت های پلن')),
                ('ops4', models.CharField(blank=True, max_length=50, null=True, verbose_name='قابلیت های پلن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': ' کارت پلن های خدمات',
                'verbose_name_plural': ' کارت پلن های خدمات',
            },
        ),
        migrations.CreateModel(
            name='plan_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تایتل برای پلن ها')),
                ('des', models.CharField(max_length=200, verbose_name='توضیحات پلن ها')),
            ],
            options={
                'verbose_name': 'پلن های خدمات',
                'verbose_name_plural': 'پلن های خدمات',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'چه خدماتی ارائه می دهم؟', 'verbose_name_plural': 'چه خدماتی ارائه می دهم؟'},
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(default='default-icon', max_length=50, verbose_name='اسم به اینگلیسی برای ایکون'),
        ),
        migrations.AlterField(
            model_name='services',
            name='url',
            field=models.URLField(default='default-url', verbose_name='لینک برای بیشتر بخوانید'),
        ),
    ]
