# Generated by Django 5.2 on 2025-09-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_plan_cart_plan_title_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_title',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال /غیر فعال'),
        ),
        migrations.AlterField(
            model_name='plan_title',
            name='des',
            field=models.CharField(max_length=400, verbose_name='توضیحات پلن ها'),
        ),
    ]
