# Generated by Django 5.2 on 2025-09-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='سلام من ... هستم')),
            ],
        ),
        migrations.CreateModel(
            name='home_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1_of_3', models.CharField(max_length=50, verbose_name='متن قبل باکس سبز')),
                ('title_2_of_3', models.CharField(max_length=50, verbose_name='متن باکس سبز')),
                ('title_3_of_3', models.CharField(max_length=50, verbose_name='متن بعد باکس سبز')),
                ('descreption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('complate_projects', models.CharField(max_length=50, verbose_name='پروژه های کامل')),
                ('customer', models.CharField(max_length=50, verbose_name='مشتری')),
                ('experience', models.CharField(max_length=50, verbose_name='تجربه')),
            ],
            options={
                'verbose_name': 'تنظیمات خانه',
                'verbose_name_plural': ' تنظیمات خانه',
            },
        ),
    ]
