# Generated by Django 5.2 on 2025-09-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hi',
            options={'verbose_name': 'سلام من ... هستم', 'verbose_name_plural': 'سلام من ... هستم'},
        ),
        migrations.AddField(
            model_name='home_model',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/ غیر فعال'),
        ),
    ]
