# Generated by Django 5.2 on 2025-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hi_options_home_model_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='عکس در خانه'),
        ),
    ]
