# Generated by Django 5.2 on 2025-09-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/ غیر فعال'),
        ),
    ]
