# Generated by Django 5.2 on 2025-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_me_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='عکس در درباره ما')),
                ('title_1_of_3', models.CharField(max_length=50, verbose_name='متن قبل  سبز')),
                ('title_2_of_3', models.CharField(max_length=50, verbose_name='متن باکس سبز')),
                ('title_3_of_3', models.CharField(max_length=50, verbose_name='متن بعد  سبز')),
                ('descreption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('ability1', models.CharField(max_length=50, verbose_name='تیک توانایی ها 1')),
                ('ability2', models.CharField(max_length=50, verbose_name='تیک توانایی ها 2')),
                ('ability3', models.CharField(max_length=50, verbose_name='تیک توانایی ها 3')),
                ('ability4', models.CharField(max_length=50, verbose_name='تیک توانایی ها 4')),
            ],
        ),
    ]
