# Generated by Django 5.2 on 2025-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me_model',
            options={'verbose_name': ' درباره من سکشن 1', 'verbose_name_plural': ' درباره من سکشن 1'},
        ),
        migrations.AddField(
            model_name='about_me_model',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال /غیر فعال'),
        ),
    ]
