# Generated by Django 5.2 on 2025-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_me_model_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='مهارتت')),
                ('image', models.ImageField(upload_to='ability_logo/', verbose_name='لوگو مهارت')),
                ('percent', models.CharField(max_length=50, verbose_name='درصد بلدی شما')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
        ),
    ]
