# Generated by Django 5.2 on 2025-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_my_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_ability',
            options={'verbose_name': ' مهارت های من سکشن 2', 'verbose_name_plural': ' مهارت های من سکشن 2'},
        ),
        migrations.RemoveField(
            model_name='my_ability',
            name='image',
        ),
        migrations.AddField(
            model_name='my_ability',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم مهارت به اینگلیسی برای ایکون'),
        ),
    ]
