# Generated by Django 5.2 on 2025-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_my_ability_options_remove_my_ability_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_ability',
            name='icon',
            field=models.CharField(default='default-icon', max_length=50, verbose_name='اسم مهارت به اینگلیسی برای ایکون'),
        ),
    ]
