# Generated by Django 5.2 on 2025-10-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio/', verbose_name='عکس نمونه کار')),
                ('title', models.CharField(max_length=100, verbose_name='اسم')),
                ('type1', models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی')),
                ('url_github', models.URLField(verbose_name='لینک گیت هاب پروژه')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': ' نمونه کار ها',
                'verbose_name_plural': ' نمونه کار ها',
            },
        ),
        migrations.CreateModel(
            name='prot_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تایتل برای پلن ها')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': 'تایتل نمونه کار ها',
                'verbose_name_plural': 'تایتل نمونه کار ها',
            },
        ),
    ]
