# Generated by Django 5.2 on 2025-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='type3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='type4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی'),
        ),
    ]
