# Generated by Django 5.2 on 2025-10-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_type2_portfolio_type3_portfolio_type4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='url_github',
            field=models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب پروژه'),
        ),
    ]
